### PR TITLE
Update ResizableArray.java

### PR DESCRIPTION
**Pull request by ZeroMoreFree**
since the loop "while(length + remaining > capacity)" will return -1 or let the capacity > length + remaining

then if the program is not return -1 , "capacity - length > remaining " come into existence
so it is no need for you to use the Math.min function to get a result

### CODE REVIEW

**Review by jjenkov — COMMENTED** [review]
Hey, I am sorry, but I don't understand what  you are talking about. Could you please be a bit more specific?

**Comment by jjenkov** [comment]
Ah, now I get it. What you are saying is, that since the while-loop above will either continue running until capacity > length + remaining (or return -1 if expansion fails), by the time the while loop exits and we get to copying the bytes, it is guaranteed that length + remaining < capacity, so there will always be space for the bytes from the ByteBuffer in the ResizableArrayBuffer...

You are right! Thanks! :-)

**Comment by ZeroMoreFree** [comment]
That's exactly what I want to say. Thank you for your reply. It's a good tutorial

**Comment by jjenkov** [comment]
Merged in! Thanks again! :-)

**Pull request merged**
